import pandas as pd
from snakemake.utils import validate
from snakemake.utils import min_version
from pathlib import Path
import yaml

min_version("6.15.1")

##### load config and sample sheets #####

configfile: "config/config.yaml"

# set up sample
samples = pd.read_csv(config["samples"], dtype=object).set_index("genome_id", drop=False)
samples.index.names = ["genome_id"]

# set up units
units = pd.read_csv(config["units"], dtype=object).set_index("genome_id", drop=False)

##### Wildcard constraints #####
wildcard_constraints:
    sample="|".join(samples.index),
    unit="|".join(units["unit"]),

##### Helper functions #####

STRAINS = samples.genome_id.to_list()
GFF = {k: v for (k,v) in units.annotations.to_dict().items()}
FNA = {k: v for (k,v) in units.assembly.to_dict().items()}

##### Target rules #####
rule all:
    input:
        expand('data/interim/prokka/{strains}/{strains}.gbk', strains=STRAINS)

##### Modules #####
include: "rules/gff_parsing.smk"